AWSTemplateFormatVersion: 2010-09-09
Description: ALB for listening https requests and forwarding to EC2

Parameters:
  VPCStack:
    Type: String
    Default: llm-app-vpc
  SGStack:
    Type: String
    Default: llm-app-sg
  EC2Stack:
    Type: String
    Default: llm-app-ec2
  CertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: acm-certificate-arn
    NoEcho: true

Resources:
  FrontLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref AWS::StackName
      Subnets:
        - Fn::ImportValue: !Sub ${VPCStack}-PublicSubnet
        - Fn::ImportValue: !Sub ${VPCStack}-PublicSubnet-2
      SecurityGroups: 
        - Fn::ImportValue: !Sub ${SGStack}-SecurityGroupLB

  FrontLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FrontLB
      Port: 80
      Protocol: HTTP 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref FrontLBTargetGroup
#        - Type: redirect
#          RedirectConfig:
#            Protocol: HTTPS
#            Port: 443
#            Host: '#{host}'
#            Path: '/#{path}'
#            Query: '#{query}'
#            StatusCode: HTTP_301
    
  FrontLBListenerHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FrontLB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontLBTargetGroup

  FrontLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-tg
      VpcId:
        Fn::ImportValue: !Sub ${VPCStack}-VPCID
      Port: 80
      Protocol: HTTP
      HealthCheckEnabled: true
      HealthCheckPath: /signin
      Targets:
        - Id:
            Fn::ImportValue: !Sub ${EC2Stack}-LLMAppServer

Outputs:
  FrontLBEndpoint:
    Value: !GetAtt FrontLB.DNSName
    Export:
      Name: !Sub ${AWS::StackName}-Endpoint

